# Generated by Django 2.1.4 on 2018-12-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoxPasswords', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='email',
            field=models.CharField(default='example@aol.com', max_length=255),
        ),
    ]
