# Generated by Django 2.1.4 on 2018-12-17 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoxPasswords', '0002_accounts_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memos',
            name='content',
            field=models.TextField(),
        ),
    ]
