# Generated by Django 2.1.4 on 2019-02-23 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FoxPasswords', '0003_auto_20181217_0140'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='usernameFox',
            field=models.CharField(default='unknown_username ', max_length=255),
        ),
    ]
